services:
  db:
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
    image: postgres:13
    volumes:
    - ./data/db:/var/lib/postgresql/data
version: '3'
