# nixpacks.toml

[build]
providers = ["nodejs", "python"]

# Define the frontend build configuration
[build.frontend]
path = "./frontend"
build_command = "npm install && npm run build"
start_command = "npm start"

# Define the backend build configuration
[build.backend]
path = "./backend"
build_command = "pip install -r requirements.txt"
start_command = "python app.py"
